version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements-dev.txt

      - run:
          name: install package
          command: |
            . ~/venv/bin/activate
            pip install -e .

      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            script/test
